/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadorapostfija;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Polker
 */
public class CalculadoraPost extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraPost
     */
    double a = 0, b = 0;
    boolean AllowPoint = true;
    boolean liberar = false;
    boolean operado = false;

    public CalculadoraPost() {
        initComponents();
        ListenerEnter le = new ListenerEnter();
        this.enter.addActionListener(le);
        //**************************************
        ManejadorNumeros mn = new ManejadorNumeros();
        this.boton0.addActionListener(mn);
        this.boton1.addActionListener(mn);
        this.boton2.addActionListener(mn);
        this.boton3.addActionListener(mn);
        this.boton4.addActionListener(mn);
        this.boton5.addActionListener(mn);
        this.boton6.addActionListener(mn);
        this.boton7.addActionListener(mn);
        this.boton8.addActionListener(mn);
        this.boton9.addActionListener(mn);
        //*************************************
        ManejadorPunto mp = new ManejadorPunto();
        this.botonPunto.addActionListener(mp);
        //*************************************
        ManejadorOperador mo = new ManejadorOperador();
        this.botonSuma.addActionListener(mo);
        this.botonResta.addActionListener(mo);
        this.botonMulti.addActionListener(mo);
        this.botonDivi.addActionListener(mo);
        //*************************************

    }

    public void liberar() {
        if (this.liberar) {
            this.pantalla1.setText("");
            this.pantalla2.setText("");
            this.resultado.setText("");
            this.operacion.setText("");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla1 = new javax.swing.JTextField();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonDivi = new javax.swing.JButton();
        botonMulti = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        botonSuma = new javax.swing.JButton();
        signo = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        pantalla2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        operacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla1.setEditable(false);
        pantalla1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pantalla1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantalla1.setText("0");

        boton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton7.setText("7");

        boton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton8.setText("8");

        boton9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton9.setText("9");

        botonDivi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonDivi.setText("/");

        botonMulti.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonMulti.setText("*");

        boton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton6.setText("6");

        boton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton5.setText("5");

        boton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton4.setText("4");

        boton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton1.setText("1");

        boton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton2.setText("2");

        boton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton3.setText("3");

        boton0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton0.setText("0");

        botonIgual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonIgual.setText("=");

        botonResta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonResta.setText("--");

        botonSuma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonSuma.setText("+");

        signo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        signo.setText("+/-");

        clear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clear.setText("C");

        Delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Delete.setText("Del");

        botonPunto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonPunto.setText(".");

        resultado.setEditable(false);
        resultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultado.setText("0");

        enter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enter.setText("ENTER");

        pantalla2.setEditable(false);
        pantalla2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pantalla2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantalla2.setText("0");

        operacion.setEditable(false);
        operacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        operacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pantalla1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pantalla2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(operacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(enter))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(botonDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(botonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(signo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(botonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(botonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(botonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(pantalla1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(pantalla2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(operacion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(enter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraPost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonDivi;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMulti;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSuma;
    private javax.swing.JButton clear;
    private javax.swing.JButton enter;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField operacion;
    private javax.swing.JTextField pantalla1;
    private javax.swing.JTextField pantalla2;
    private javax.swing.JTextField resultado;
    private javax.swing.JButton signo;
    // End of variables declaration//GEN-END:variables
public class ListenerEnter implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            liberar();
            String data1 =pantalla1.getText();
            String data2 =pantalla2.getText();
            String res =resultado.getText();
            System.out.println("Valor data1: "+data1+"--");
            System.out.println("Valor data2: "+data2+"--");
            System.out.println("Valor res: "+res+"--");
            if (data1.equals("0")||data1.equals("")) {
                pantalla1.setText(data2);
                pantalla2.setText("");
                AllowPoint = true;
            } else {
                if(operado&&!liberar){
                    pantalla2.setText(res);
                    resultado.setText("");
                    pantalla1.setText("");
                    
                }else if(!operado){
                    new ManejadorResultado().actionPerformed(e);
                }else{
                      
                JOptionPane.showMessageDialog(null, "Debes de seleccionar la operacion");
                }
            }

        }

    }

    public class ManejadorNumeros implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            liberar();
            JButton btn = (JButton) e.getSource();
            if(pantalla2.getText().equals("0")){
                pantalla2.setText(btn.getText());
            }else{
            pantalla2.setText(pantalla2.getText() + btn.getText());
            }
        }

    }

    public class ManejadorPunto implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            liberar();
            if (AllowPoint) {
                JButton btn = (JButton) e.getSource();
                pantalla2.setText(pantalla2.getText() + btn.getText());
                AllowPoint = false;
            }

        }

    }

    public class ManejadorOperador implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            JButton btn = (JButton) e.getSource();

            operacion.setText(btn.getText());

        }

    }

    public class ManejadorResultado implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            liberar();
            if (pantalla1.getText().equals("")) {
                pantalla1.setText("0");

            } else if (pantalla2.getText().equals("")) {
                pantalla2.setText("0");

            }
            a = Double.parseDouble(pantalla1.getText());
            b = Double.parseDouble(pantalla2.getText());

            String res = "";
            switch (operacion.getText()) {
                case "+":
                    a += b;
                    break;
                case "-":
                    a -= b;
                    break;
                case "*":
                    a *= b;
                    break;
                case "/":
                    if (b == 0) {
                        res = "No se puede Divir por 0";
                        liberar = true;
                    } else {
                        a /= b;
                    }
                    break;
            }

            if (res.equals("")) {
                res = a + "";
            }

            resultado.setText(res);
            AllowPoint = true;
            operado = true;

        }

    }

}
